language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
# PyYAML is a test dependency but Travis doesn't read tests_require from setup.py
install:
  - "python setup.py -q install"
  - "pip install PyYAML"
  - "pip install coverage"
  - "pip install coveralls"
# command to run tests
script:
  - "nosetests tests"
  - "coverage run --source=syncset setup.py test"
after_success:
    coveralls
